extends "res://tests/test_scene.gd"
## Actual current-campaign input path; legacy scene fixtures use their saved rules.
func touch(index: int, at: Vector2, down: bool) -> void:
 var event=InputEventScreenTouch.new();event.index=index;event.position=at;event.pressed=down
 root.push_input(event,true);Input.flush_buffered_events()
func drag(index: int, at: Vector2) -> void:
 var event=InputEventScreenDrag.new();event.index=index;event.position=at
 root.push_input(event,true);Input.flush_buffered_events()
func run_scene() -> void:
 var game=load("res://scenes/frontier.tscn").instantiate()
 root.add_child(game)
 await frames(8)
 game.knight.position=Vector2(30,430)
 await frames(3)
 key(KEY_J,true);await frames(2);key(KEY_J,false)
 check(game.sim.hero.attack_remaining==0,"unlit knight cannot attack via actual keyboard")
 check(game.knight.visual.unarmed,"unlit knight renders without sword")
 check(game.knight.visual.self_modulate.a==0,"unarmed body does not overlap idle sword after campaign physics")
 key(KEY_E,true);await frames(2);key(KEY_E,false);await frames(3)
 check(game.sim.frontier.city_level==1,"E draws the sword and lights camp")
 check(not game.knight.visual.unarmed,"ignition enables armed appearance")
 check(game.hud.dashboard.immersive,"new journey hides numerical top dashboard")
 game.knight.position.x=game.sim.world.sites.workshop
 await frames(4)
 var wallet: int=game.sim.pouch.amount
 key(KEY_E,true);await frames(2);key(KEY_E,false);await frames(2)
 check(not game.sim.investments.is_empty(),"keyboard release keeps sockets for grace period")
 await frames(62)
 check(game.sim.investments.is_empty(),"expired keyboard payment returns to world")
 check(game.sim.pouch.amount==wallet-1,"refund flies through world before collection")
 game.sim.hero.stamina=0
 key(KEY_J,true);await frames(2);key(KEY_J,false)
 check(game.sim.hero.attack_remaining==0 and game.knight.visual.fatigue.visible,"empty attack stamina also shows a tired resting pose")
 key(KEY_SHIFT,true);key(KEY_D,true)
 await frames(3)
 check(game.sim.travel.exhausted and game.knight.velocity.x==0,"fast-run exhaustion physically stops knight")
 check(game.knight.visual.breathing and game.knight.visual.fatigue.visible,"exhaustion renders authored hunched pose")
 check(game.knight.visual.self_modulate.a==0,"fatigue body does not overlap standing body after campaign physics")
 var purse: Rect2=game.hud.immersive_feedback.purse.bounds
 var safe: Rect2=game.hud.safe_rect()
 check(purse.position.y<safe.position.y+32 and purse.end.x>safe.end.x-32,"purse occupies the top-right safe corner")
 check(game.hud.get_node("pause").position.x<safe.position.x+32,"menu occupies the top-left safe corner")
 check(not game.hud.fullscreen_button.visible,"fullscreen stays inside the closed menu")
 game.knight.position.x+=200;await frames(2)
 check(game.hud.immersive_feedback.purse.bounds==purse,"purse stays fixed when knight moves")
 key(KEY_D,false);key(KEY_SHIFT,false)
 game.sim.workforce.elapsed=155
 game.hud.present_world(game.sim,false,game.knight.position.x,true)
 check(game.hud.guide_view.hint.is_empty(),"ghost retires after early guidance")
 game.sim._hit_structure({"kind":"core","x":30.0},10)
 game.hud.present_world(game.sim,false,game.knight.position.x,true)
 check(game.hud.immersive_feedback._alarm>0,"core damage produces global alarm cue")
 game.restart();game.knight.position=Vector2(30,430)
 game.hud.control_mode=2;await frames(3)
 check(not game.hud.guide_view.touch_hint,"desktop guide chooses keyboard prompts")
 check(game.hud.guide_view._guide_label.text.contains(tr("按住 E 投入／互動")),"desktop ghost names actual interaction key")
 game.hud.control_mode=1;game.hud._layout();await frames(3)
 check(game.hud.guide_view.touch_hint,"phone guide chooses drag prompts")
 touch(20,Vector2(100,260),true);drag(20,Vector2(100,320));await frames(2)
 touch(20,Vector2(100,320),false);await frames(3)
 check(game.sim.frontier.city_level==1,"phone downward gesture ignites camp")
 game.knight.position.x=game.sim.world.sites.workshop;await frames(3)
 touch(21,Vector2(450,210),true);drag(21,Vector2(450,270));await frames(2)
 touch(21,Vector2(450,270),false);await frames(2)
 check(not game.sim.investments.is_empty(),"phone release preserves slots for a second")
 var tool_count: int=game.sim.world.tools.hammer
 var slots_at: Vector2=game.get_viewport().get_canvas_transform()*Vector2(game.sim.world.sites.workshop,320)
 touch(22,slots_at,true);await frames(2);touch(22,slots_at,false);await frames(2)
 check(game.sim.world.tools.hammer==tool_count+1,"single tap on suspended sockets completes the phone payment")
 touch(23,Vector2(450,210),true);drag(23,Vector2(450,270));await frames(2)
 touch(23,Vector2(450,270),false);await frames(2)
 await frames(62)
 check(game.sim.investments.is_empty() and game.sim.pouch.ground_total()>0,"phone grace expiry refunds incomplete tool purchase physically")
 check(not game.hud.immersive_feedback.purse.bounds.intersects(Rect2(game.hud.get_node("attack").position,Vector2(64,64))),"fixed purse does not cover touch attack button")
 var menu_at: Vector2=game.hud.get_node("pause").position+Vector2(32,32)
 touch(30,menu_at,true);await frames(2);touch(30,menu_at,false);await frames(2)
 check(game.paused and game.hud.options_menu.visible,"hamburger touch opens options and pauses play")
 touch(31,menu_at,true);await frames(2);touch(31,menu_at,false);await frames(2)
 check(not game.paused and not game.hud.options_menu.visible,"hamburger touch closes options and resumes play")
 game.queue_free();await process_frame
 print("Immersive scene assertions: %d; failures: %d"%[assertions,failures])
 quit(0 if failures==0 else 1)
