extends "res://tests/test_mobile_scene.gd"
func run_scene() -> void:
 var scene=load("res://scenes/frontier.tscn").instantiate();root.add_child(scene)
 await frames(8)
 scene.set_physics_process(false)
 scene.sim.interact(30,"hall")
 for relic in scene.sim.modules.relics:scene.sim.advance(0.1,relic.x)
 scene.sim.pouch.amount=12
 scene.knight.position=Vector2(scene.sim.world.sites.drill,430)
 scene.sim.advance(0.1,scene.knight.position.x)
 scene._physics_process(1.0/30)
 key(KEY_F,true);key(KEY_F,false);scene._physics_process(1.0/30)
 check(scene.paused and scene.hud.module_menu.visible,"F opens module selection at the upgrade station")
 check(not scene.hud.options_menu.visible and not scene.hud.get_node("Refuge").visible,"selection does not overlap settings or offer combat practice")
 scene.hud.module_menu._buttons[0].pressed.emit()
 check(scene.sim.modules.equipped=="arc" and scene.sim.pouch.amount==4,"choosing a previous module charges eight crystals")
 scene.hud.module_menu._close.pressed.emit();scene._physics_process(1.0/30)
 key(KEY_K,true);key(KEY_K,false);scene._physics_process(1.0/30)
 check(scene.sim.effects.any(func(e):return e.kind=="module_arc"),"quick K press activates the equipped ability")
 var paid: float=scene.sim.hero.stamina
 key(KEY_K,true);key(KEY_K,false);scene._physics_process(1.0/30)
 check(scene.sim.hero.stamina>=paid,"cooldown cannot charge stamina again")
 scene.sim.modules.ready_tick=0;scene.sim.hero.stamina=100;scene.sim.effects.clear()
 touch(10,Vector2(180,330),true);touch(11,Vector2(340,330),true)
 drag(10,Vector2(180,260));drag(11,Vector2(340,260));scene._physics_process(1.0/30)
 check(scene.sim.effects.any(func(e):return e.kind=="module_arc"),"real two-finger upward events activate the ability")
 touch(10,Vector2(180,260),false);touch(11,Vector2(340,260),false)
 check(scene.sim.investments.is_empty(),"special gesture never invests a crystal")
 scene.sim.clock.is_night=true;scene.sim.clock.remaining=30;scene._physics_process(1.0/30)
 check(scene._lantern.visible and scene._lantern._light.energy>0.7,"night light follows the knight and illuminates the world")
 scene.sim.clock.is_night=false;scene.sim.clock.remaining=scene.sim.clock.day_seconds*0.5;scene._physics_process(1.0/30)
 check(not scene._lantern.visible,"lamp fades away in daytime")
 check(scene._water.visible and scene._water._surface.polygon.size()==4,"expanded water fills the visible river area")
 scene.queue_free();await frames(3)
 print("Module scene assertions: %d; failures: %d" % [assertions,failures]);quit(0 if failures==0 else 1)
