extends "res://tests/test_crystal_scene.gd"
## Reuses the real input helpers; this suite exercises held investment gestures.
func run_test() -> void:
	var scene=load("res://scenes/frontier.tscn").instantiate();scene.tuning=scene.tuning.duplicate();scene.tuning.immersive_loop=false
	root.add_child(scene)
	await frames(6)
	scene.knight.position.x=30
	await frames(3)
	key(KEY_E,true)
	await frames(8)
	check(scene.sim.context(30).paid==1,"E immediately fills the first campfire slot")
	check(scene.view.investment_progress>0 and scene.view.focus_key=="hall","held E displays progress on its locked target")
	await frames(ceili(scene.tuning.investment_hold_delay*60)+12)
	check(scene.sim.frontier.city_level==1,"holding E finishes the camp without repeated tapping")
	await frames(50)
	check(scene.sim.pouch.amount==10,"keeping E held does not start another project")
	key(KEY_E,false)
	await frames(3)

	scene.knight.position=Vector2(scene.sim.world.sites.workshop,430)
	await frames(4)
	key(KEY_E,true)
	key(KEY_SPACE,true)
	await frames(3)
	check(scene.sim.pouch.amount==9 and scene.knight.is_on_floor(),"removed jump cannot block a valid grounded payment")
	key(KEY_E,false)
	key(KEY_SPACE,false)
	await frames(70)
	preload("res://tests/touch_gesture.gd").start(root)
	await frames(8)
	check(scene.sim.world.tools.hammer==1,"downward gesture immediately completes the already partially funded tool")
	await frames(70)
	check(scene.sim.world.tools.hammer==1 and scene.sim.pouch.amount==8,"held downward gesture buys exactly one tool")
	preload("res://tests/touch_gesture.gd").finish(root)
	await frames(3)
	check(not scene.hud.interact_held,"releasing gesture clears held input")

	scene.knight.position=Vector2(scene.sim.world.sites.wall,430)
	await frames(4)
	key(KEY_E,true)
	await frames(6)
	var amount: int=scene.sim.pouch.amount
	key(KEY_ESCAPE,true)
	await frames(2)
	key(KEY_ESCAPE,false)
	await frames(40)
	check(scene.paused and scene.sim.pouch.amount==amount,"pause stops held payment before the next crystal")
	key(KEY_ESCAPE,true)
	await frames(2)
	key(KEY_ESCAPE,false)
	await frames(40)
	check(not scene.paused and scene.sim.pouch.amount==amount,"resuming with E still held cannot spend")
	key(KEY_E,false)
	await frames(3)
	key(KEY_E,true)
	await frames(3)
	check(scene.sim.pouch.amount==amount-1,"fresh E resumes the wall's preserved slots")
	key(KEY_SPACE,true)
	await frames(4)
	key(KEY_SPACE,false)
	await frames(70)
	check(scene.sim.world.wall.pending,"removed jump leaves the held wall payment uninterrupted")
	key(KEY_E,false)
	await frames(3)
	key(KEY_E,true)
	await frames(3)
	key(KEY_E,false)
	check(scene.sim.world.wall.pending,"pending wall order stays intact after another press")
	scene.queue_free()
	await process_frame
	print("Investment scene assertions: %d; failures: %d" % [assertions,failures])
	quit(0 if failures==0 else 1)
